# Uncomment the next line to define a global platform for your project
platform :ios, '12.1'

target 'GoogleSignInSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GoogleSignInSample
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'Firebase/Core'
end
